# docker-compose.yml (Updated to use pushed images from Docker Hub)

services:
  # Backend Service Configuration
  backend:
    # build: ./backend # Replaced build with image
    image: bharateesha04/registration-backend:v1.0 # Use the image from Docker Hub
    container_name: reg-backend-compose-prod # Changed name slightly (optional)
    env_file:
      - ./backend/.env # Still needed for Supabase keys
    ports:
      - "3001:3001"
    # volumes: removed for non-development running
    # restart: unless-stopped

  # Frontend Service Configuration
  frontend:
    # build: # Replaced build with image
    #   context: ./frontend
    #   target: build-stage
    image: bharateesha04/registration-frontend:v1.0 # Use the image from Docker Hub
    container_name: reg-frontend-compose-prod # Changed name slightly (optional)
    ports:
      - "8080:80" # Map host 8080 to container's Nginx port 80
    depends_on:
      - backend
    # environment: removed
    # volumes: removed
    # command: removed (will use default Nginx command from image)
    # restart: unless-stopped